<?xml version="1.0"?>
<package format="2">
  <name>RTTLIO</name>
  <version>1.0.0</version>
  <description>Tightly-coupled WiFi RTT/LiDAR/IMU integration for indoor/outdoor localization</description>

  <maintainer email="user@todo.todo">user</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>message_generation</depend>
  <depend>message_runtime</depend>
  <depend>wifi_rtt_msgs</depend>

</package>
